apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: permittering-kalkulator
  namespace: permittering-og-nedbemanning
  labels:
    team: permittering-og-nedbemanning
spec:
  image: {{image}}
  team: permittering-og-nedbemanning
  port: 3000
  ingresses:
    - https://permittering-kalkulator.dev.nav.no/permittering-kalkulator
  liveness:
    path: /permittering-kalkulator/internal/isAlive
    initialDelay: 50
  readiness:
    path: /permittering-kalkulator/internal/isReady
    initialDelay: 50
  env:
    - name: NODE_EXTRA_CA_CERTS
      value: "/etc/ssl/ca-bundle.pem"