apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: arbeidsgiver-permittering
  namespace: default
  labels:
    team: arbeidsgiver
spec:
  image: {{image}}
  team: arbeidsgiver
  port: 3000
  ingresses:
    - {{ingress}}
  liveness:
    path: /arbeidsgiver-permittering/internal/isReady
    initialDelay: 10
  readiness:
    path: /arbeidsgiver-permittering/internal/isReady
    initialDelay: 10
  vault:
    enabled: true
